DROP TABLE IF EXISTS IMAGES;
CREATE TABLE IMAGES (
    id IDENTITY NOT NULL primary key,
    fileName VARCHAR(100) NOT NULL,
    contentType VARCHAR(100) NOT NULL,
    label VARCHAR(100) NOT NULL,
    objects VARCHAR(MAX)
);
